apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadjwiu3249-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadjwiu3249-tenant-component
    app.kubernetes.io/part-of: loadjwiu3249-tenant-app
  name: loadjwiu3249-tenant-component
  namespace: loadjwiu3249-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: loadjwiu3249-tenant-component
    weight: null
status: {}
